#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Export Git hook params
export GIT_PARAMS=$*
echo "[STARTED] git提交信息校验中..."
echo "ⓘ   提交规范: 遵循Conventional Commits规范。"
echo "ⓘ   规范详情: https://juejin.cn/post/6985500205554597918"
npx --no-install fabric verify-commit
echo "[STARTED] git提交信息校验完成..."
